package = "demo"
# readme_ext = "md"
scripts_path = "/usr/bin"
request = "/usr/bin/curl -Lo"

[args]

[dev]
# repository = "python"
# tag = "3.9-alpine"
image = "python:3.9-alpine"
poetry_version = "1.1.4"
# [dev.env]
# [dev.args]
# [dev.poetry_extras]
[[dev.reqs]]
"apk add --no-cache" = [
    "gcc",
    "libressl-dev",
    "musl-dev",
    "libffi-dev",
    "curl",
    "git",
    "python3-dev",
]
[prod]

repository = "python"
tag = "3.9-alpine"
# image = "python:3.9-alpine"
# [prod.env]
# [prod.args]
# [prod.poetry_extras]
entrypoint_script = "./wait-for-it.sh"
cmd = "./wait-for-it.sh"

[[prod.reqs]]
"apt-get update" = []
"apt-get install --no-cache --no-install-recommends" = ["libcurl", "libsdl"]

[[prod.reqs]]
"apk add --no-cache" = ["libcurl", "libsdl"]
