cmd = "--help"
dev_image="python"
dev_tag="3.9-alpine"

poetry_version = "1.1.4"
request_file = "/usr/bin/curl -Lo"
scripts_path = "/usr/bin"
package = "demo"
prod_image = "python"
prod_tag = "3.9-alpine"
entrypoint_script = "wait-for-it.sh"

[[build_reqs]]
"apk add --no-cache" = [
    "gcc",
    "libressl-dev",
    "musl-dev",
    "libffi-dev",
    "curl",
    "git",
    "python3-dev",
]


[[runtime_reqs]]
"apk add --no-cache" = ["libcurl"]
